name: Notify Discord on Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: z3y/discord-notify-action@main
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
