name: Notify Discord on Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        uses: gist.github.com/z3y/648b596712de4998f296e40c2dcf06a0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
